site_name: LangGraph
site_description: Build language agents as graphs
site_url: https://langchain-ai.github.io/langgraph/
theme:
  name: material
  custom_dir: overrides
  logo: static/wordmark.png
  favicon: static/favicon.png
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
  - scheme: default
    primary: white
    accent: gray
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: grey
    accent: white
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  font:
    text: "Public Sans"
    code: "Roboto Mono"
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://api.python.langchain.com/en/latest/objects.inv
          options:
            members_order: source 
            allow_inspection: true
            heading_level: 3
            show_bases: true
            summary: true
            inherited_members: true
            # merge_init_into_class: true
            selection:
                docstring_style: google
            docstring_section_style: list
            show_root_toc_entry: false 
            # show_signature_annotations: true
            # show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
  - mkdocs-jupyter:
      ignore_h1_titles: true
      execute: false
      include_source: True
      include_requirejs: true
  # TODO: Add minify plugin once it works alright with code block copying
  # - minify:
  #     minify_html: true
nav:
  - Home: 
      - 'index.md'
      - Quick Start: how-tos/docs/quickstart.ipynb
  - Tutorials:
      - 'tutorials/index.md'
      - Agent Executor:
            - "Base": tutorials/agent_executor/base.ipynb
            - "High-Level": tutorials/agent_executor/high-level.ipynb
      - Chat Agent Executor:
            - "Base": tutorials/chat_agent_executor_with_function_calling/base.ipynb
            - "High-Level": tutorials/chat_agent_executor_with_function_calling/high-level.ipynb
            - "Tool Node": tutorials/chat_agent_executor_with_function_calling/prebuilt-tool-node.ipynb
            - "High-Level Tools": tutorials/chat_agent_executor_with_function_calling/high-level-tools.ipynb
      - Use cases:
          - Chatbots:
              - Customer Support: tutorials/chatbots/customer-support.ipynb
              - Info Gathering: tutorials/chatbots/information-gather-prompting.ipynb
          - Code Assistant: tutorials/code_assistant/langgraph_code_assistant.ipynb
          - Web Navigation: tutorials/web-navigation/web_voyager.ipynb
          - Multi-Agent Systems:
              - Collaboration: tutorials/multi_agent/multi-agent-collaboration.ipynb
              - Supervision: tutorials/multi_agent/agent_supervisor.ipynb
              - Hierarchical Teams: tutorials/multi_agent/hierarchical_agent_teams.ipynb
          - RAG:
              - tutorials/rag/langgraph_adaptive_rag.ipynb
              - tutorials/rag/langgraph_adaptive_rag_cohere.ipynb
              - tutorials/rag/langgraph_adaptive_rag_local.ipynb
              - tutorials/rag/langgraph_agentic_rag.ipynb
              - tutorials/rag/langgraph_crag.ipynb
              - tutorials/rag/langgraph_crag_local.ipynb
              - tutorials/rag/langgraph_self_rag.ipynb
              - tutorials/rag/langgraph_self_rag_local.ipynb
          - Web Research (STORM): tutorials/storm/storm.ipynb
          - Planning Agents:
              - Plan-and-Execute: tutorials/plan-and-execute/plan-and-execute.ipynb
              - Reasoning w/o Observation: tutorials/rewoo/rewoo.ipynb
              - LLMCompiler: tutorials/llm-compiler/LLMCompiler.ipynb
          - Reflection & Critique:
              - Basic Reflection: tutorials/reflection/reflection.ipynb
              - Reflexion: tutorials/reflexion/reflexion.ipynb
              - Language Agent Tree Search: tutorials/lats/lats.ipynb
              - Self-Discovering Agent: tutorials/self-discover/self-discover.ipynb
          - Evaluation & Analysis:
              - Chatbot Eval via Sim:
                  - Agent-based: tutorials/chatbot-simulation-evaluation/agent-simulation-evaluation.ipynb
                  - Dataset-based: tutorials/chatbot-simulation-evaluation/langsmith-agent-simulation-evaluation.ipynb

  - "How-to Guides":
      - 'how-tos/index.md'
      - Core:
          - "Quick Start": how-tos/docs/quickstart.ipynb
          - "State Management": how-tos/state-model.ipynb
          - "Async Execution": how-tos/async.ipynb
          - "Streaming Responses": how-tos/streaming-tokens.ipynb
          - "Human-in-the-Loop": how-tos/human-in-the-loop.ipynb
          - "Persistence": how-tos/persistence.ipynb
          - "Time Travel": how-tos/time-travel.ipynb
          - "Visualization": how-tos/visualization.ipynb
          - "Pydantic State": how-tos/state-model.ipynb
          - "Subgraphs": how-tos/subgraph.ipynb
          - "Branching": how-tos/branching.ipynb
      - Chat Agent (Function Calling):
          - Human-in-the-Loop: how-tos/chat_agent_executor_with_function_calling/human-in-the-loop.ipynb
          - Force Tool First: how-tos/chat_agent_executor_with_function_calling/force-calling-a-tool-first.ipynb
          - Respond in Format: how-tos/chat_agent_executor_with_function_calling/respond-in-format.ipynb
          - Dynamic Direct Return: how-tos/chat_agent_executor_with_function_calling/dynamically-returning-directly.ipynb
          - Manage Agent Steps: how-tos/chat_agent_executor_with_function_calling/managing-agent-steps.ipynb
      - AgentExecutor:
          - Human-in-the-Loop: how-tos/agent_executor/human-in-the-loop.ipynb
          - Force Tool First: how-tos/agent_executor/force-calling-a-tool-first.ipynb
          - Manage Agent Steps: how-tos/agent_executor/managing-agent-steps.ipynb
      - Persistance:
          - "Persistance in Postgres": how-tos/persistence_postgres.ipynb

  - Reference:
      - Graphs: reference/graphs.md
      - Checkpointing: reference/checkpoints.md
      - Prebuilt Components: reference/prebuilt.md
  

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: langchain-ai 
      repo: langgraph
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
extra_css:
  - css/mkdocstrings.css